AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  weather-sam-api
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  WeatherAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: WeatherSamAPI
      Description: SAM API utilizing the OpenWeatherMap API. 
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          weatherApiKey: f234fg34g453gb45634f34534f345ds4
          geocodeApiKey: d23fv45y645hbtyj678ibdfghb456456
      Architectures:
        - x86_64
      Events:
        ListEvent:
          Type: Api
          Properties:
            Path: /weather
            Method: GET
        PostEvent:
          Type: Api
          Properties:
            Path: /weather
            Method: POST
        GetEvent:
          Type: Api
          Properties:
            Path: /weather/{id}
            Method: GET
        PutEvent:
          Type: Api
          Properties:
            Path: /weather/{id}
            Method: PUT
        DeleteEvent:
          Type: Api
          Properties:
            Path: /weather/{id}
            Method: DELETE